# Form implementation generated from reading ui file 'racecard.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RaceCard(object):
    def setupUi(self, RaceCard):
        RaceCard.setObjectName("RaceCard")
        RaceCard.resize(845, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(RaceCard)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(parent=RaceCard)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Downloads/sync-regular-24.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=RaceCard)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Downloads/printer-solid-24.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(parent=RaceCard)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 825, 447))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(RaceCard)
        QtCore.QMetaObject.connectSlotsByName(RaceCard)

    def retranslateUi(self, RaceCard):
        _translate = QtCore.QCoreApplication.translate
        RaceCard.setWindowTitle(_translate("RaceCard", "Form"))
        self.pushButton.setText(_translate("RaceCard", "Fetch"))
        self.pushButton_2.setText(_translate("RaceCard", "Download"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RaceCard = QtWidgets.QWidget()
    ui = Ui_RaceCard()
    ui.setupUi(RaceCard)
    RaceCard.show()
    sys.exit(app.exec())
